// Mateen and Eyouel 
// February 12, 2024
// Period 5
// Hunt the Wumpus - User Interface Class

import javax.swing.*;    

public class UI{
    ///////////////////////
    // Properties & Fields
    //////////////////////

    ///////////////////////
    // Constructor(s)
    //////////////////////
    public static UI(){
public class ButtonTest {
    //just testing how this ui stuff works  
public static void main(String[] args) {  
    JFrame f=new JFrame("Button Test");  
    JButton b=new JButton("Click Here");  
    b.setBounds(50,100,95,30);  
    f.add(b);  
    f.setSize(400,400);  
    f.setLayout(null);  
    f.setVisible(true);   
}  
}  

    }

    ///////////////////////
    // Methods
    //////////////////////
}